### ISSUE TITLE
Migration from GitHub commit to v0.10.0 fails with Path service error and confusing API changes

### ISSUE THREAD

**Issue by SamuelLHuber** [nounder/solid-deno#50]
## Environment
- **effect-start version**: 0.10.0 (upgraded from `github:nounder/effect-start#82e9982`)
- **effect version**: 3.19.8 (upgraded from 3.18.4)
- **Runtime**: Bun 1.3.1
- **Platform**: macOS (Darwin 24.6.0)

## Summary
When upgrading from effect-start GitHub commit #82e9982 to v0.10.0, the application fails to start with multiple API incompatibilities and missing service dependencies. The README documentation appears to be outdated, showing APIs that don't exist in 0.10.0.

### 1. Removed/Non-existent APIs
The README shows examples using APIs that don't exist in v0.10.0:
- `Start.make()` - Function doesn't exist
- `Start.router()` - Function doesn't exist

**Example from README** (lines 17-34):
\`\`\`typescript
export default Start.make(
  Start.router(() => import("./routes/_manifest")),
  Start.bundleClient({ ... }),
)
\`\`\`

This pattern fails with: `TypeError: Start.router is not a function`

### 2. Path Service Dependency Not Automatically Provided

When using \`Router.layerFiles()\` (or its alias \`FileRouter.layer()\`), the Path service from \`@effect/platform\` is required but not automatically provided by the framework.

**Error:**
\`\`\`
Error: Service not found: @effect/platform/Path
  at Sync (/node_modules/effect/dist/esm/internal/fiberRuntime.js:941:19)
  at runLoop (/node_modules/effect/dist/esm/internal/fiberRuntime.js:1138:34)
\`\`\`

**Root Cause:** 
In \`src/FileRouter.ts:140-162\`, \`layerManifest()\` uses \`FileSystemExtra.watchSource()\` which requires the FileSystem service, which in turn requires the Path service. These services are not automatically provided in the layer hierarchy.

**Code Location:**
\`\`\`typescript
// FileRouter.ts:140-150
return Layer.scopedDiscard(
  Effect.gen(function*() {
    yield* FileRouterCodegen.update(routesPath, manifestFilename)
    
    const stream = Function.pipe(
      FileSystemExtra.watchSource({
        path: routesPath,
        filter: (e) => !e.path.includes("node_modules"),
      }),
      Stream.onError((e) => Effect.logError(e)),
    )
    // ...
  }),
)
\`\`\`

### 3. \`FileRouter.layer()\` Type Signature Confusion

The \`FileRouter.layer()\` function expects an object with \`{ load, path }\` properties, but the error message when passing incorrect arguments is confusing:

**Expected Signature** (\`src/FileRouter.ts:165-168\`):
\`\`\`typescript
export function layer(options: {
  load: () => Promise<Router.RouterManifest>
  path: string
})
\`\`\`

**Error when called incorrectly:**
\`\`\`typescript
FileRouter.layer(import.meta.resolve("./routes"))
// Results in: TypeError: undefined is not an object (evaluating 'manifestPath.startsWith')
\`\`\`

This error occurs at \`src/FileRouter.ts:129:7\` because \`options.path\` is undefined when a string is passed instead of an object.

## Steps to Reproduce

1. Create a project with database layers and platform service dependencies:
\`\`\`typescript
// server.ts
import { BunContext, BunFileSystem, BunPath } from "@effect/platform-bun"
import { Layer } from "effect"
import { Router, Start } from "effect-start"
import { BunTailwindPlugin } from "effect-start/bun"

const clientBundle = Start.bundleClient({
  entrypoints: ["./src/index.html"],
  plugins: [BunTailwindPlugin.make()],
  target: "browser",
})

export default Start.layer(
  BunContext.layer,
  BunPath.layer,
  BunFileSystem.layer,
  // Custom app layers here (database, etc.)
  Router.layerFiles({
    load: () => import("./routes"),
    path: import.meta.resolve("./routes"),
  }),
  clientBundle,
)
\`\`\`

2. Run the server: \`bun run dev\`

3. Observe the Path service error

## Expected Behavior

The router layer should either:
1. Automatically have access to required platform services (Path, FileSystem), OR
2. Documentation should clearly explain the service dependency requirements

## Actual Behavior

- Application fails with \`Service not found: @effect/platform/Path\` error
- No clear documentation on how to properly wire platform service dependencies
- README contains outdated examples with non-existent APIs

## Workaround Attempted

Providing platform layers via \`Layer.provide()\` doesn't resolve the issue:
\`\`\`typescript
const routerLayer = Layer.provide(
  Router.layerFiles({
    load: () => import("./routes"),
    path: import.meta.resolve("./routes"),
  }),
  Layer.mergeAll(BunPath.layer, BunFileSystem.layer, BunContext.layer),
)
\`\`\`

This still results in the Path service error because the service needs to be available at layer construction time, not just at runtime.

## Questions

1. What is the correct way to use \`Router.layerFiles()\` in 0.10.0 with platform service dependencies?
2. Should \`Start.layer()\` automatically provide platform services?
3. Can the README be updated to remove references to \`Start.make()\` and \`Start.router()\`?
4. Should there be a migration guide for upgrading from the GitHub commit version to v0.10.0?

## Additional Context

The \`bun-fullstack\` example in the repository works because it doesn't have additional layer dependencies (database, caching, etc.), so the layering is simpler. Applications with more complex layer hierarchies encounter this issue.

**Working example structure** (\`examples/bun-fullstack/src/server.ts:6-11\`):
\`\`\`typescript
export default Start.layer(
  Router.layerFiles({
    load: () => import("./routes"),
    path: import.meta.resolve("./routes"),
  }),
)
\`\`\`

**Comment by nounder** [comment]
Readme has been updated with new API usage. See [bun-fullstack example](https://github.com/nounder/effect-start/tree/main/examples/bun-fullstack) for new usage pattern, including adding dynamic head elements, like meta, that you may need:

https://github.com/nounder/effect-start/blob/6758e768b83be433fd6c774c6e3bc6240c9a1826/examples/bun-fullstack/src/routes/admin/layer.tsx#L15

Next time when creating an issue, instead of feeding me un-formatted un-reviewed ai slop, please use more meatware.
